/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.LayoutManager;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import modelo.TimbiricheBoard;
import utils.JugadorDTO;
import vistaModelo.IVistaModeloTablero;
import vistaModelo.VistaModeloTablero;

/**
 *
 * @author berly
 */
public class Tablero extends javax.swing.JFrame {

    Font customFontTitulos = new Font("Just Me Again Down Here", Font.BOLD, 50);
    Font customFontSubT = new Font("Just Me Again Down Here", Font.PLAIN, 30);

    IVistaModeloTablero vistaModeloTablero;

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        jLabelTurno.setFont(customFontTitulos);
        btnSalir.setFont(customFontTitulos);
        jLJugador1.setFont(customFontSubT);
        jLPtsJ1.setFont(customFontSubT);
        lblPts.setFont(customFontSubT);

        this.jLJugador1.setVisible(false);
        this.pnlColorJ1.setVisible(false);
        this.jLPtsJ1.setVisible(false);
        // PRUEBAAA, VA EN MODELO SE SABE 
        this.pnlTablero.add(new TimbiricheBoard());
        //    this.pnlTablero.getComponent(0).setBounds(-50, -40, 972, 673);
        vistaModeloTablero = new VistaModeloTablero();
        vistaModeloTablero.imprimirJugadores();
        moduloJugadores();

    }

    public Tablero(List<String> nombres) {
        initComponents();
        jLabelTurno.setFont(customFontTitulos);
        btnSalir.setFont(customFontTitulos);
        jLJugador1.setFont(customFontSubT);
        jLPtsJ1.setFont(customFontSubT);
        lblPts.setFont(customFontSubT);
        // PRUEBAAA, VA EN MODELO SE SABE 
        this.pnlTablero.add(new TimbiricheBoard());
    }

    private void moduloJugadores() {
        System.out.println("ras");
        int paddingVertical = 0;
        JugadorDTO[] jugadoresDTO = vistaModeloTablero.recuperarJugadores();

        for (JugadorDTO jugador : jugadoresDTO) {
            System.out.println("aqui");
            JLabel nomJugador = new JLabel(jugador.getNickname());
            nomJugador.setBounds(this.jLJugador1.getX(), this.jLJugador1.getY() + paddingVertical, 96, 32);
            nomJugador.setVisible(true);
            System.out.println(nomJugador.getBounds());
            this.pnlFondo.add(nomJugador);

            JPanel pnlPts=new JPanel();
            pnlPts.setBackground(generarColor(jugador.getColor()));
            pnlPts.setBounds(this.pnlColorJ1.getX()+30,this.pnlColorJ1.getY()+paddingVertical,52,26);
            pnlPts.setVisible(true);
            
            JLabel pts=new JLabel("0");
            pts.setForeground(Color.WHITE);
            pts.setBounds(this.jLPtsJ1.getBounds());
            pts.setVisible(true);
            pnlPts.add(pts);
            
            this.pnlFondo.add(pnlPts);
            paddingVertical += 50;

        }
    }
    
    public Color generarColor(String color) {
        String rgb[] = color.split(",");
        return new Color(Integer.parseInt(rgb[0]), Integer.parseInt(rgb[1]), Integer.parseInt(rgb[2]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnlFondo = new javax.swing.JPanel();
        jLabelTurno = new javax.swing.JLabel();
        pnlColorJ1 = new javax.swing.JPanel();
        jLPtsJ1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLJugador1 = new javax.swing.JLabel();
        lblPts = new javax.swing.JLabel();
        pnlTablero = new javax.swing.JPanel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(255, 207, 210));

        jLabelTurno.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        jLabelTurno.setText("Turno de:");

        pnlColorJ1.setBackground(new java.awt.Color(246, 255, 197));

        jLPtsJ1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLPtsJ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPtsJ1.setText("0");

        javax.swing.GroupLayout pnlColorJ1Layout = new javax.swing.GroupLayout(pnlColorJ1);
        pnlColorJ1.setLayout(pnlColorJ1Layout);
        pnlColorJ1Layout.setHorizontalGroup(
            pnlColorJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPtsJ1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );
        pnlColorJ1Layout.setVerticalGroup(
            pnlColorJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPtsJ1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        btnSalir.setBackground(new java.awt.Color(207, 186, 240));
        btnSalir.setFont(new java.awt.Font("Yu Gothic", 3, 12)); // NOI18N
        btnSalir.setText("Salir");

        jLJugador1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLJugador1.setText("Jugador 1");

        lblPts.setText("Pts:");

        pnlTablero.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlTableroLayout = new javax.swing.GroupLayout(pnlTablero);
        pnlTablero.setLayout(pnlTableroLayout);
        pnlTableroLayout.setHorizontalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 872, Short.MAX_VALUE)
        );
        pnlTableroLayout.setVerticalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(pnlTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                                    .addComponent(jLabelTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(72, 72, 72))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                                    .addComponent(lblPts, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)))
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addComponent(jLJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlColorJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(pnlTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(jLabelTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPts)
                        .addGap(28, 28, 28)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLJugador1)
                            .addComponent(pnlColorJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(525, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlFondo.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        Tablero tab = new Tablero();
        tab.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLJugador1;
    private javax.swing.JLabel jLPtsJ1;
    private javax.swing.JLabel jLabelTurno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblPts;
    private javax.swing.JPanel pnlColorJ1;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlTablero;
    // End of variables declaration//GEN-END:variables
}
